runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
- url: /images
  static_dir: images
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
